In [1]:
# dependencies
import random
import pandas as pd
import requests
import json
import numpy as np
import glob

In [2]:
file_15Q1 = "all_files/2015Q1-capitalbikeshare-tripdata.csv"
data_15Q1 = pd.read_csv(file_15Q1,index_col=None, header=0)
data_15Q1.head(2)

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,2389,2015-01-01 00:02:44,2015-01-01 00:42:33,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W01140,Casual
1,2394,2015-01-01 00:02:46,2015-01-01 00:42:41,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W00612,Casual

In [5]:
bike_location_file = "all_files/location.csv"
bike_location_df = pd.read_csv(bike_location_file,index_col=None, header=0)
bike_location_df.head(2)

,OBJECTID,ID,ADDRESS,TERMINAL_NUMBER,LATITUDE,LONGITUDE,INSTALLED,LOCKED,INSTALL_DATE,REMOVAL_DATE,TEMPORARY_INSTALL,NUMBER_OF_BIKES,NUMBER_OF_EMPTY_DOCKS,X,Y,SE_ANNO_CAD_DATA,OWNER
0,223143627,434,Town Center Pkwy & Bowman Towne Dr,32210,38.962524,-77.361902,YES,NO,NaN,NaN,NO,8,7,368634.8196,143908.1787,NaN,NaN
1,223143628,435,Reston Regional Library,32211,38.962095,-77.358815,YES,NO,NaN,NaN,NO,7,7,368902.1739,143859.4999,NaN,NaN

In [7]:
bike_renamed_df = bike_location_df.rename(columns={"TERMINAL_NUMBER":"Start station number"})
bike_renamed_df.head(2)

,OBJECTID,ID,ADDRESS,Start station number,LATITUDE,LONGITUDE,INSTALLED,LOCKED,INSTALL_DATE,REMOVAL_DATE,TEMPORARY_INSTALL,NUMBER_OF_BIKES,NUMBER_OF_EMPTY_DOCKS,X,Y,SE_ANNO_CAD_DATA,OWNER
0,223143627,434,Town Center Pkwy & Bowman Towne Dr,32210,38.962524,-77.361902,YES,NO,NaN,NaN,NO,8,7,368634.8196,143908.1787,NaN,NaN
1,223143628,435,Reston Regional Library,32211,38.962095,-77.358815,YES,NO,NaN,NaN,NO,7,7,368902.1739,143859.4999,NaN,NaN

In [9]:
merge_table = pd.merge(data_15Q1, bike_renamed_df, on="Start station number", how="left")
merge_table.head(2)

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type,OBJECTID,...,LOCKED,INSTALL_DATE,REMOVAL_DATE,TEMPORARY_INSTALL,NUMBER_OF_BIKES,NUMBER_OF_EMPTY_DOCKS,X,Y,SE_ANNO_CAD_DATA,OWNER
0,2389,2015-01-01 00:02:44,2015-01-01 00:42:33,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W01140,Casual,223143453.0,...,NO,NaN,NaN,NO,3.0,23.0,398792.6549,136047.8572,NaN,DC
1,2394,2015-01-01 00:02:46,2015-01-01 00:42:41,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W00612,Casual,223143453.0,...,NO,NaN,NaN,NO,3.0,23.0,398792.6549,136047.8572,NaN,DC

In [11]:
merge_table_some_col = merge_table[['Duration', 'Start date', 'End date', 'Start station number', 
                                'Start station', 'End station number', 'End station', 'Bike number',
                                'Member type', 'ADDRESS', 'LATITUDE', 'LONGITUDE']]
merge_table_some_col.head(2)

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type,ADDRESS,LATITUDE,LONGITUDE
0,2389,2015-01-01 00:02:44,2015-01-01 00:42:33,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W01140,Casual,Constitution Ave & 2nd St NW/DOL,38.892275,-77.013917
1,2394,2015-01-01 00:02:46,2015-01-01 00:42:41,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W00612,Casual,Constitution Ave & 2nd St NW/DOL,38.892275,-77.013917

In [25]:
merge_table_rename = merge_table_some_col.rename(columns={'Duration': 'Duration', 'Start date': 'Start date', 
                                                           'End date': 'End date', 'Start station number': 'Start station #', 
                                                           'Start station': 'Start station', 'LATITUDE' : 'Start Station Lat', 
                                                           'LONGITUDE': 'Start Station Lng', 'End station number': 'End station #', 
                                                           'End station': 'End station', 'Bike number': 'Bike number',
                                                           'Member type': 'Member type'
                                                          })
merge_table_rename.head()

,Duration,Start date,End date,Start station #,Start station,End station #,End station,Bike number,Member type,ADDRESS,Start Station Lat,Start Station Lng
0,2389,2015-01-01 00:02:44,2015-01-01 00:42:33,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W01140,Casual,Constitution Ave & 2nd St NW/DOL,38.892275,-77.013917
1,2394,2015-01-01 00:02:46,2015-01-01 00:42:41,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W00612,Casual,Constitution Ave & 2nd St NW/DOL,38.892275,-77.013917
2,468,2015-01-01 00:04:32,2015-01-01 00:12:20,31204,20th & E St NW,31234,20th & O St NW / Dupont South,W01226,Member,20th & E St NW,38.896300,-77.045000
3,348,2015-01-01 00:07:18,2015-01-01 00:13:06,31602,Park Rd & Holmead Pl NW,31117,15th & Euclid St NW,W20216,Member,Park Rd & Holmead Pl NW,38.930800,-77.031500
4,980,2015-01-01 00:09:39,2015-01-01 00:26:00,31247,Jefferson Dr & 14th St SW,31241,Thomas Circle,W21005,Casual,Jefferson Dr & 14th St SW,38.888553,-77.032429

In [26]:
renamed_df2 = bike_renamed_df.rename(columns={"Start station number" : "End station #"})
renamed_df2.head(2)

,OBJECTID,ID,ADDRESS,End station #,LATITUDE,LONGITUDE,INSTALLED,LOCKED,INSTALL_DATE,REMOVAL_DATE,TEMPORARY_INSTALL,NUMBER_OF_BIKES,NUMBER_OF_EMPTY_DOCKS,X,Y,SE_ANNO_CAD_DATA,OWNER
0,223143627,434,Town Center Pkwy & Bowman Towne Dr,32210,38.962524,-77.361902,YES,NO,NaN,NaN,NO,8,7,368634.8196,143908.1787,NaN,NaN
1,223143628,435,Reston Regional Library,32211,38.962095,-77.358815,YES,NO,NaN,NaN,NO,7,7,368902.1739,143859.4999,NaN,NaN

In [27]:
merge_table2 = pd.merge(merge_table_rename, renamed_df2, on="End station #", how="left")
merge_table2

,Duration,Start date,End date,Start station #,Start station,End station #,End station,Bike number,Member type,ADDRESS_x,...,LOCKED,INSTALL_DATE,REMOVAL_DATE,TEMPORARY_INSTALL,NUMBER_OF_BIKES,NUMBER_OF_EMPTY_DOCKS,X,Y,SE_ANNO_CAD_DATA,OWNER
0,2389,2015-01-01 00:02:44,2015-01-01 00:42:33,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W01140,Casual,Constitution Ave & 2nd St NW/DOL,...,NO,NaN,NaN,NO,13.0,12.0,397091.5598,137127.8517,NaN,DC
1,2394,2015-01-01 00:02:46,2015-01-01 00:42:41,31271,Constitution Ave & 2nd St NW/DOL,31254,15th & K St NW,W00612,Casual,Constitution Ave & 2nd St NW/DOL,...,NO,NaN,NaN,NO,13.0,12.0,397091.5598,137127.8517,NaN,DC
2,468,2015-01-01 00:04:32,2015-01-01 00:12:20,31204,20th & E St NW,31234,20th & O St NW / Dupont South,W01226,Member,20th & E St NW,...,NO,NaN,NaN,NO,2.0,15.0,396116.0948,137894.7812,NaN,DC
3,348,2015-01-01 00:07:18,2015-01-01 00:13:06,31602,Park Rd & Holmead Pl NW,31117,15th & Euclid St NW,W20216,Member,Park Rd & Holmead Pl NW,...,NO,NaN,NaN,NO,1.0,14.0,396947.6146,139495.7125,NaN,DC
4,980,2015-01-01 00:09:39,2015-01-01 00:26:00,31247,Jefferson Dr & 14th St SW,31241,Thomas Circle,W21005,Casual,Jefferson Dr & 14th St SW,...,NO,NaN,NaN,NO,3.0,29.0,397181.0576,137560.7509,NaN,DC
5,932,2015-01-01 00:10:33,2015-01-01 00:26:06,31247,Jefferson Dr & 14th St SW,31241,Thomas Circle,W01126,Casual,Jefferson Dr & 14th St SW,...,NO,NaN,NaN,NO,3.0,29.0,397181.0576,137560.7509,NaN,DC
6,387,2015-01-01 00:12:26,2015-01-01 00:18:53,31222,New York Ave & 15th St NW,31202,14th & R St NW,W20464,Member,New York Ave & 15th St NW,...,NO,NaN,NaN,NO,15.0,4.0,397217.3280,138342.1249,NaN,DC
7,321,2015-01-01 00:13:01,2015-01-01 00:18:22,31017,Wilson Blvd & N Uhle St,31022,Clarendon Metro / Wilson Blvd & N Highland St,W20416,Member,Wilson Blvd & N Uhle St,...,NO,NaN,NaN,NO,6.0,11.0,391768.7767,135561.9429,NaN,NaN
8,294,2015-01-01 00:16:52,2015-01-01 00:21:47,31214,17th & Corcoran St NW,31241,Thomas Circle,W21178,Member,17th & Corcoran St NW,...,NO,NaN,NaN,NO,3.0,29.0,397181.0576,137560.7509,NaN,DC
9,2646,2015-01-01 00:17:03,2015-01-01 01:01:10,31249,Jefferson Memorial,31231,14th & D St NW / Ronald Reagan Building,W21343,Casual,Jefferson Memorial,...,NO,NaN,NaN,NO,13.0,12.0,397257.2084,136296.7868,NaN,DC
10,607,2015-01-01 00:18:20,2015-01-01 00:28:27,31104,Adams Mill & Columbia Rd NW,31107,Lamont & Mt Pleasant NW,W01241,Casual,Adams Mill & Columbia Rd NW,...,NO,NaN,NaN,NO,2.0,15.0,396635.8432,140447.1824,NaN,DC
11,670,2015-01-01 00:19:42,2015-01-01 00:30:52,31042,Market Square / King St & Royal St,31048,King St Metro South,W00976,Casual,Market Square / King St & Royal St,...,NO,NaN,NaN,NO,4.0,19.0,394725.9552,126446.5207,NaN,NaN
12,544,2015-01-01 00:20:06,2015-01-01 00:29:10,31115,Columbia Rd & Georgia Ave NW,31506,1st & Rhode Island Ave NW,W01087,Member,Columbia Rd & Georgia Ave NW,...,NO,NaN,NaN,NO,1.0,14.0,398934.2350,138616.7862,NaN,DC
13,631,2015-01-01 00:20:08,2015-01-01 00:30:40,31042,Market Square / King St & Royal St,31048,King St Metro South,W00494,Casual,Market Square / King St & Royal St,...,NO,NaN,NaN,NO,4.0,19.0,394725.9552,126446.5207,NaN,NaN
14,484,2015-01-01 00:20:19,2015-01-01 00:28:23,31104,Adams Mill & Columbia Rd NW,31107,Lamont & Mt Pleasant NW,W00075,Member,Adams Mill & Columbia Rd NW,...,NO,NaN,NaN,NO,2.0,15.0,396635.8432,140447.1824,NaN,DC
15,116,2015-01-01 00:20:28,2015-01-01 00:22:25,31241,Thomas Circle,31266,11th & M St NW,W00715,Member,Thomas Circle,...,NO,NaN,NaN,NO,6.0,12.0,397646.2168,137528.0736,NaN,DC
16,1153,2015-01-01 00:21:47,2015-01-01 00:41:00,31249,Jefferson Memorial,31014,Lynn & 19th St North,W01244,Member,Jefferson Memorial,...,NO,NaN,NaN,NO,23.0,6.0,393841.5616,136609.6397,NaN,NaN
17,611,2015-01-01 00:23:18,2015-01-01 00:33:30,31114,18th St & Wyoming Ave NW,31245,7th & R St NW / Shaw Library,W21894,Member,18th St & Wyoming Ave NW,...,NO,NaN,NaN,NO,0.0,14.0,398078.5324,138317.4472,NaN,DC
18,359,2015-01-01 00:23:40,2015-01-01 00:29:40,31201,15th & P St NW,31266,11th & M St NW,W01222,Member,15th & P St NW,...,NO,NaN,NaN,NO,6.0,12.0,397646.2168,137528.0736,NaN,DC
19,928,2015-01-01 00:25:38,2015-01-01 00:41:06,31202,14th & R St NW,31314,34th & Water St NW,W00392,Member,14th & R St NW,...,NO,NaN,NaN,NO,4.0,13.0,394130.5181,137314.0994,NaN,DC
20,2104,2015-01-01 00:25:49,2015-01-01 01:00:54,31249,Jefferson Memorial,31231,14th & D St NW / Ronald Reagan Building,W21548,Casual,Jefferson Memorial,...,NO,NaN,NaN,NO,13.0,12.0,397257.2084,136296.7868,NaN,DC
21,829,2015-01-01 00:28:17,2015-01-01 00:42:07,31506,1st & Rhode Island Ave NW,31116,California St & Florida Ave NW,W00219,Member,1st & Rhode Island Ave NW,...,NO,NaN,NaN,NO,2.0,17.0,396477.3416,138877.7017,NaN,DC
22,619,2015-01-01 00:28:44,2015-01-01 00:39:03,31121,Calvert St & Woodley Pl NW,31104,Adams Mill & Columbia Rd NW,W00258,Member,Calvert St & Woodley Pl NW,...,NO,NaN,NaN,NO,3.0,11.0,396307.5467,139451.0267,NaN,DC
23,513,2015-01-01 00:28:57,2015-01-01 00:37:30,31234,20th & O St NW / Dupont South,31101,14th & V St NW,W00521,Member,20th & O St NW / Dupont South,...,NO,NaN,NaN,NO,7.0,20.0,397216.2090,138859.5351,NaN,DC
24,587,2015-01-01 00:29:08,2015-01-01 00:38:55,31121,Calvert St & Woodley Pl NW,31104,Adams Mill & Columbia Rd NW,W21251,Member,Calvert St & Woodley Pl NW,...,NO,NaN,NaN,NO,3.0,11.0,396307.5467,139451.0267,NaN,DC
25,1258,2015-01-01 00:29:25,2015-01-01 00:50:23,31108,4th & M St SW,31204,20th & E St NW,W20945,Member,4th & M St SW,...,NO,NaN,NaN,NO,0.0,14.0,396096.3238,136495.5341,NaN,DC
26,325,2015-01-01 00:31:08,2015-01-01 00:36:34,31610,Eastern Market / 7th & North Carolina Ave SE,31626,15th St & Massachusetts Ave SE,W20894,Member,Eastern Market / 7th & North Carolina Ave SE,...,NO,NaN,NaN,NO,0.0,14.0,401425.5418,135497.8497,NaN,DC
27,317,2015-01-01 00:31:13,2015-01-01 00:36:30,31610,Eastern Market / 7th & North Carolina Ave SE,31626,15th St & Massachusetts Ave SE,W21250,Member,Eastern Market / 7th & North Carolina Ave SE,...,NO,NaN,NaN,NO,0.0,14.0,401425.5418,135497.8497,NaN,DC
28,959,2015-01-01 00:32:49,2015-01-01 00:48:49,31300,Van Ness Metro / UDC,31200,Massachusetts Ave & Dupont Circle NW,W21374,Member,Van Ness Metro / UDC,...,NO,NaN,NaN,NO,13.0,26.0,396149.1179,138027.4199,NaN,DC
29,122,2015-01-01 00:33:08,2015-01-01 00:35:11,31261,21st St & Constitution Ave NW,31220,US Dept of State / Virginia Ave & 21st St NW,W21962,Casual,21st St & Constitution Ave NW,...,NO,NaN,NaN,NO,1.0,14.0,395958.5759,136342.3012,NaN,DC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423689,367,2015-03-31 23:26:44,2015-03-31 23:32:52,31245,7th & R St NW / Shaw Library,31503,Florida Ave & R St NW,W01284,Member,7th & R St NW / Shaw Library,...,NO,NaN,NaN,NO,0.0,14.0,398829.1647,138304.0906,NaN,DC
423690,461,2015-03-31 23:26:49,2015-03-31 23:34:30,31265,5th St & Massachusetts Ave NW,31244,4th & E St SW,W21336,Member,5th St & Massachusetts Ave NW,...,NO,NaN,NaN,NO,0.0,19.0,398486.4164,135142.6413,NaN,DC
423691,1109,2015-03-31 23:28:06,2015-03-31 23:46:36,31222,New York Ave & 15th St NW,31007,Crystal City Metro / 18th & Bell St,W21729,Member,New York Ave & 15th St NW,...,NO,NaN,NaN,NO,10.0,7.0,395561.9645,132178.1755,NaN,NaN
423692,1285,2015-03-31 23:28:42,2015-03-31 23:50:07,31231,14th & D St NW / Ronald Reagan Building,31258,Lincoln Memorial,W20742,Member,14th & D St NW / Ronald Reagan Building,...,NO,NaN,NaN,NO,5.0,17.0,395711.8918,135602.2305,NaN,DC
423693,105,2015-03-31 23:29:35,2015-03-31 23:31:21,31105,14th & Harvard St NW,31119,14th & Belmont St NW,W00519,Member,14th & Harvard St NW,...,NO,NaN,NaN,NO,6.0,9.0,397234.8156,139245.1718,NaN,DC
423694,130,2015-03-31 23:29:39,2015-03-31 23:31:50,31623,Columbus Circle / Union Station,31616,3rd & H St NE,W00736,Member,Columbus Circle / Union Station,...,NO,NaN,NaN,NO,5.0,13.0,399830.9372,136951.0386,NaN,DC
423695,483,2015-03-31 23:30:04,2015-03-31 23:38:08,31623,Columbus Circle / Union Station,31632,15th & F St NE,W01065,Member,Columbus Circle / Union Station,...,NO,NaN,NaN,NO,0.0,19.0,401424.8240,136594.0523,NaN,DC
423696,768,2015-03-31 23:30:28,2015-03-31 23:43:16,31232,7th & F St NW / National Portrait Gallery,31632,15th & F St NE,W00621,Member,9th & F St NW / National Portrait Gallery,...,NO,NaN,NaN,NO,0.0,19.0,401424.8240,136594.0523,NaN,DC
423697,452,2015-03-31 23:30:34,2015-03-31 23:38:07,31623,Columbus Circle / Union Station,31622,13th & D St NE,W00078,Member,Columbus Circle / Union Station,...,NO,NaN,NaN,NO,9.0,21.0,401072.8391,136331.6850,NaN,DC
423698,952,2015-03-31 23:30:57,2015-03-31 23:46:50,31229,New Hampshire Ave & T St NW,31108,4th & M St SW,W00310,Member,New Hampshire Ave & T St NW,...,NO,NaN,NaN,NO,5.0,18.0,398455.4549,134318.9706,NaN,DC
423699,1076,2015-03-31 23:32:32,2015-03-31 23:50:28,31222,New York Ave & 15th St NW,31619,Lincoln Park / 13th & East Capitol St NE,W00545,Member,New York Ave & 15th St NW,...,NO,NaN,NaN,NO,2.0,22.0,401010.2674,135846.4614,NaN,DC
423700,546,2015-03-31 23:32:52,2015-03-31 23:41:59,31613,Eastern Market Metro / Pennsylvania Ave & 7th ...,31617,Bladensburg Rd & Benning Rd NE,W21314,Member,Eastern Market Metro / Pennsylvania Ave & 7th ...,...,NO,NaN,NaN,NO,2.0,11.0,401485.7403,136951.2872,NaN,DC
423701,192,2015-03-31 23:34:52,2015-03-31 23:38:04,31104,Adams Mill & Columbia Rd NW,31103,16th & Harvard St NW,W21789,Member,Adams Mill & Columbia Rd NW,...,NO,NaN,NaN,NO,1.0,29.0,396831.8853,139801.9194,NaN,DC
423702,434,2015-03-31 23:34:56,2015-03-31 23:42:10,31070,Arlington Blvd & Fillmore St,31035,N Quincy St & Glebe Rd,W21077,Member,Arlington Blvd & Fillmore St,...,NO,NaN,NaN,NO,3.0,8.0,390651.5592,134290.2570,NaN,NaN
423703,141,2015-03-31 23:36:19,2015-03-31 23:38:41,31252,21st St & Pennsylvania Ave NW,31212,21st & M St NW,W21573,Member,21st St & Pennsylvania Ave NW,...,NO,NaN,NaN,NO,8.0,6.0,395942.9464,137499.1239,NaN,DC
423704,326,2015-03-31 23:38:04,2015-03-31 23:43:31,31624,North Capitol St & F St NW,31612,D St & Maryland Ave NE,W20684,Member,North Capitol St & F St NW,...,NO,NaN,NaN,NO,0.0,22.0,400250.3612,136323.4017,NaN,DC
423705,307,2015-03-31 23:40:36,2015-03-31 23:45:43,31408,Takoma Metro,32010,Philadelphia & Maple Ave,W00340,Member,Takoma Metro,...,NO,NaN,NaN,NO,9.0,6.0,399017.7920,145928.1627,NaN,NaN
423706,435,2015-03-31 23:40:43,2015-03-31 23:47:59,31227,13th St & New York Ave NW,31221,18th & M St NW,W21757,Member,13th St & New York Ave NW,...,NO,NaN,NaN,NO,19.0,8.0,396376.1856,137468.6086,NaN,DC
423707,227,2015-03-31 23:40:49,2015-03-31 23:44:36,31616,3rd & H St NE,31614,11th & H St NE,W00736,Member,3rd & H St NE,...,NO,NaN,NaN,NO,2.0,17.0,400747.4721,136903.4496,NaN,DC
423708,447,2015-03-31 23:44:26,2015-03-31 23:51:54,31205,21st & I St NW,31214,17th & Corcoran St NW,W21929,Member,21st & I St NW,...,NO,NaN,NaN,NO,1.0,15.0,396643.5820,138249.2114,NaN,DC
423709,276,2015-03-31 23:45:53,2015-03-31 23:50:29,31200,Massachusetts Ave & Dupont Circle NW,31229,New Hampshire Ave & T St NW,W01182,Member,Massachusetts Ave & Dupont Circle NW,...,NO,NaN,NaN,NO,2.0,19.0,396688.8408,138631.0609,NaN,DC
423710,474,2015-03-31 23:45:59,2015-03-31 23:53:54,31256,10th & E St NW,31600,5th & K St NW,W21817,Member,10th & E St NW,...,NO,NaN,NaN,NO,7.0,9.0,398349.5948,137242.9379,NaN,DC
423711,226,2015-03-31 23:46:50,2015-03-31 23:50:36,31017,Wilson Blvd & N Uhle St,31079,Lee Hwy & N Cleveland St,W21637,Member,Wilson Blvd & N Uhle St,...,NO,NaN,NaN,NO,7.0,7.0,392045.8923,136347.7067,NaN,NaN
423712,284,2015-03-31 23:47:55,2015-03-31 23:52:40,31117,15th & Euclid St NW,31121,Calvert St & Woodley Pl NW,W00441,Member,15th & Euclid St NW,...,NO,NaN,NaN,NO,2.0,15.0,395660.2519,139524.3987,NaN,DC
423713,466,2015-03-31 23:48:31,2015-03-31 23:56:18,31232,7th & F St NW / National Portrait Gallery,31616,3rd & H St NE,W21481,Member,9th & F St NW / National Portrait Gallery,...,NO,NaN,NaN,NO,5.0,13.0,399830.9372,136951.0386,NaN,DC
423714,416,2015-03-31 23:52:52,2015-03-31 23:59:48,31239,Rhode Island & Connecticut Ave NW,31268,12th & U St NW,W01162,Member,Rhode Island & Connecticut Ave NW,...,NO,NaN,NaN,NO,3.0,28.0,397559.6888,138769.1720,NaN,DC
423715,410,2015-03-31 23:54:29,2015-04-01 00:01:20,31623,Columbus Circle / Union Station,31632,15th & F St NE,W21214,Member,Columbus Circle / Union Station,...,NO,NaN,NaN,NO,0.0,19.0,401424.8240,136594.0523,NaN,DC
423716,857,2015-03-31 23:55:03,2015-04-01 00:09:21,31623,Columbus Circle / Union Station,31506,1st & Rhode Island Ave NW,W00995,Member,Columbus Circle / Union Station,...,NO,NaN,NaN,NO,1.0,14.0,398934.2350,138616.7862,NaN,DC
423717,122,2015-03-31 23:56:02,2015-03-31 23:58:04,32013,Montgomery & East Ln,32002,Bethesda Ave & Arlington Rd,W21816,Member,Montgomery & East Ln,...,NO,NaN,NaN,NO,5.0,14.0,391558.5023,145912.9575,NaN,NaN
423718,203,2015-03-31 23:59:52,2015-04-01 00:03:15,31234,20th & O St NW / Dupont South,31255,24th & N St NW,W21325,Member,20th & O St NW / Dupont South,...,NO,NaN,NaN,NO,9.0,6.0,395531.3698,137639.2158,NaN,DC

In [28]:
merge_table2.columns

Index(['Duration', 'Start date', 'End date', 'Start station #',
       'Start station', 'End station #', 'End station', 'Bike number',
       'Member type', 'ADDRESS_x', 'Start Station Lat', 'Start Station Lng',
       'OBJECTID', 'ID', 'ADDRESS_y', 'LATITUDE', 'LONGITUDE', 'INSTALLED',
       'LOCKED', 'INSTALL_DATE', 'REMOVAL_DATE', 'TEMPORARY_INSTALL',
       'NUMBER_OF_BIKES', 'NUMBER_OF_EMPTY_DOCKS', 'X', 'Y',
       'SE_ANNO_CAD_DATA', 'OWNER'],
      dtype='object')

In [32]:
merge_table2_org_rename = merge_table2[['Duration', 
                                        'Start date', 
                                        'End date', 
                                        'Start station #',
                                        'Start station', 
                                        'Start Station Lat', 
                                        'Start Station Lng',                                       
                                        'End station #', 
                                        'End station', 
                                        'LATITUDE', 
                                        'LONGITUDE',
                                        'Bike number',
                                        'Member type', 
                                        'LOCKED', 
                                        'INSTALL_DATE', 
                                        'REMOVAL_DATE',
                                        'NUMBER_OF_BIKES'
                                       ]]
merge_table2_org_rename.head()

,Duration,Start date,End date,Start station #,Start station,Start Station Lat,Start Station Lng,End station #,End station,LATITUDE,LONGITUDE,Bike number,Member type,LOCKED,INSTALL_DATE,REMOVAL_DATE,NUMBER_OF_BIKES
0,2389,2015-01-01 00:02:44,2015-01-01 00:42:33,31271,Constitution Ave & 2nd St NW/DOL,38.892275,-77.013917,31254,15th & K St NW,38.902000,-77.03353,W01140,Casual,NO,NaN,NaN,13.0
1,2394,2015-01-01 00:02:46,2015-01-01 00:42:41,31271,Constitution Ave & 2nd St NW/DOL,38.892275,-77.013917,31254,15th & K St NW,38.902000,-77.03353,W00612,Casual,NO,NaN,NaN,13.0
2,468,2015-01-01 00:04:32,2015-01-01 00:12:20,31204,20th & E St NW,38.896300,-77.045000,31234,20th & O St NW / Dupont South,38.908905,-77.04478,W01226,Member,NO,NaN,NaN,2.0
3,348,2015-01-01 00:07:18,2015-01-01 00:13:06,31602,Park Rd & Holmead Pl NW,38.930800,-77.031500,31117,15th & Euclid St NW,38.923330,-77.03520,W20216,Member,NO,NaN,NaN,1.0
4,980,2015-01-01 00:09:39,2015-01-01 00:26:00,31247,Jefferson Dr & 14th St SW,38.888553,-77.032429,31241,Thomas Circle,38.905900,-77.03250,W21005,Casual,NO,NaN,NaN,3.0